=== ykparkforcs/docbook/ko/manual/lib/tmaxbook/lib/isoi18n/config/static_text/static_text_database.dtd
<!--==========================================================
    Static Text Database Document Type

    This DTD governs documents that define databases of static
    text in multiple languages for use with rendering systems.
    The database essentially provides a lookup mechanism by which
    systems can request the national-language-specific version of
    a given string. It supports both XML-markup-context related
    lookups (elements in context, attribute values), as well as
    arbitrary lookups by string key.
    
    The namespace URI for this XML vocabulary is:
    
    http://www.innodata-isogen.com/vocabularies/i18n_support/static_text_database

    Author: W. Eliot Kimber, eliot@isogen.com
            Innodata Isogen

    Copyright (c) 2003, 2004 Innodata Isogen


    $Revision: 1.1.1.1 $

    ===========================================================-->

<!-- language attribute is an ISO language or language-and-country code -->
<!ENTITY % lang     "xml:lang CDATA #REQUIRED" >

<!-- text_database is the document root element. It contains
     descriptive metadata for the database and one or more sets of
     contexts defining the translated text strings.

     Contexts may be common across all doctypes or specific to
     a particular doctype. Doctype-specific contexts override
     common contexts.

  -->
<!ELEMENT text_database
  (metadata,
   contexts_common,
   contexts_common*,
   attribute_maps_common?,
   attribute_maps_dtd_specific*)
>
<!ATTLIST text_database
  xmlns:fo
    CDATA
    #FIXED "http://www.w3.org/1999/XSL/Format"
  xmlns
    CDATA
    #FIXED "http://www.innodata-isogen.com/vocabularies/i18n_support/static_text_database"
>

<!ELEMENT metadata
  (title?,
   description?,
   copyright?,
   security?,
   revision_history?)
>

<!-- Descriptive title of the database, e.g. "Foo project generated text"
  -->
<!ELEMENT title
  (#PCDATA)
>

<!-- Contains a copyright statement for the database instance
  -->
<!ELEMENT copyright
  (p+)
>

<!-- Contains a security statement for the database instance,
     e.g., "For Internal Use Only" or some such.
  -->
<!ELEMENT security
  (p+)
>

<!-- Revision history is intended to capture the development history
     of the database itself.
  -->
<!ELEMENT revision_history
  (revision*)
>

<!-- The revision element describes a single revision to the database.
  -->
<!ELEMENT revision
  (date,
   author,
   description)
>

<!-- Contains the date the revision was made.
  -->
<!ELEMENT date
  (#PCDATA)
>

<!-- The author of the revision -->
<!ELEMENT author
  (#PCDATA)
>

<!-- A description of the revision -->
<!ELEMENT description
  (p+)
>

<!ELEMENT p
  (#PCDATA)
>

<!-- contexts_common contains all the contexts that are common to two or
     more document types. Each "context" is a binding between a specific
     element type and its static text. For each context there may be
     either text-before, text-after or both.

     Contexts can also be used for arbitrary string keys that are not
     related to any particular element type.
  -->
<!ELEMENT contexts_common
  (context*)
>

<!-- contexts_dtd_specific contains contexts that are specific to a particular
     document type. The "doctype" attribute specifies the external identifier
     of the document type to which the contexts apply.
  -->
<!ELEMENT contexts_dtd_specific
  (context*)
>
<!ATTLIST contexts_dtd_specific
  doctype
    CDATA
    #REQUIRED
>

<!-- The context element specifies the pre- and/or post-text for a given
     context, either element type or abitrary string key.

     Note that the element type named is the element type that establishes
     the unique context, not necessarily the element type to which the
     generated text is actually applied. For example, in the case of a caution
     element that contains para subelements, it would be the caution element that establishes the context (and is thus name as the value of the tagname element) even though it would be
     the para element within the caution that actually presented the generated
     text.
  -->
<!ELEMENT context
  (lookup_key,
   text_before,
   text_after,
   attribute_maps?)
>

<!-- The lookup key is either an element type name or some other
     arbitrary string.

     By convention the hat character ("^") is used to separate
     parts of compound keys.

  -->
<!ELEMENT lookup_key
  (#PCDATA)
>

<!-- Text before contains a set of items, one for each unique language,
     for the pre-text for the specified element type.

     The optional default element specifies generated text to be used
     for any language that does not have its own item.

     Text before may be empty if the element type has no pre-text.
  -->
<!ELEMENT text_before
  (default_item?,
   item*)
>

<!-- Text after contains a set of items, one for each unique language,
     for the post-text for the specified element type.

     Text after may be empty if the element type has no pre-text.
  -->
<!ELEMENT text_after
  (default_item?,
   item*)
>

<!-- Default item contains text that is used as the default for any language
     that does not have it's own item.

     Primarily intended for non-alphabetic generated text or to visually
     identify untranslated languages by using a default like "CAUTION not translated"
     or something.
  -->
<!ELEMENT default_item
  (#PCDATA |
   fo:inline)*
>

<!-- Each item element defines the generated pre- or post-text for a specific element
     for a specific language or language/country pair. By default, the country is
     "" (world-wide).
  -->
<!ELEMENT item
  (#PCDATA |
   fo:inline)*
>
<!ATTLIST item
  %lang;
>

<!-- attribute_maps provide mappings from attribute values to
     their display text in the context of a particular element type.

  -->
<!ELEMENT attribute_maps
  (attr_map+)
>

<!-- The common and doctype attribute mappings provide attribute
     value mappings that are not specific to a single element type

     When a value is looked up for a particular attribute, the
     element type's mappings are checked first, then the doctype-specific
     mappings, then the common mappings.
  -->
<!ELEMENT attribute_maps_common
  (attr_map+)
>

<!ELEMENT attribute_maps_dtd_specific
  (attr_map+)
>
<!ATTLIST attribute_maps_dtd_specific
  dtd
    CDATA
    #REQUIRED
>

<!ELEMENT attr_map
  (attr_name,
   attr_values*)
>

<!ELEMENT attr_name
  (#PCDATA)
>

<!ELEMENT attr_values
  (attr_value_map+)
>

<!ELEMENT attr_value_map
  (attr_value,
   default_item?,
   item*)
>

<!ELEMENT attr_value
  (#PCDATA |
   fo:inline)*
>

<!ELEMENT fo:inline
  (#PCDATA |
   fo:inline)*
>
<!ATTLIST fo:inline
  font-size
    CDATA
    #IMPLIED
  font-family
    CDATA
    #IMPLIED
  font-weight
    CDATA
    #IMPLIED
  font-style
    CDATA
    #IMPLIED
  text-decoration
    CDATA
    #IMPLIED
  baseline-shift
    CDATA
    #IMPLIED
  id
    NMTOKEN
    #IMPLIED
>

=== ykparkforcs/docbook/ko/manual/lib/tmaxbook/lib/isoi18n/config/static_text/static_text_database.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE text_database SYSTEM "static_text_database.dtd">
<!-- Caution: This document contains Unicode characters above
              the ASCII range. Save as "binary" in CVS and
              be careful with text editors.


     Each entry must provide the language-appropriate white space before or
     after a term when it is used in context where more complex strings are
     constructed from multiple generated text bits, such as cross references.
  -->
<text_database xmlns="http://www.innodata-isogen.com/vocabularies/i18n_support/static_text_database">
  <metadata>
    <title>Sample Static Text Database</title>
    <description>
      <p>This is a sample static text database.</p>
    </description>
    <copyright>
      <p>Copyright (C) 2003, 2004 Innodata Isogen</p>
      <p>This sample may be used to create derivative text databases without restriction.</p>
    </copyright>
    <security>
      <p>For Public Use</p>
    </security>
    <revision_history>
      <revision>
        <date>2003-03-24</date>
        <author>W. Eliot Kimber, ISOGEN Internation, LLC</author>
        <description>
          <p>Created initial sample of static text database.</p>
          <p>All the text samples were translated using the AltaVista babel fish service (http://babelfish.altavista.com/babelfish/tr).</p>
        </description>
      </revision>
    </revision_history>
  </metadata>
  <contexts_common>
    <context>
      <lookup_key>#contents</lookup_key>
      <text_before>
        <default_item>{#contents not translated}</default_item>
        <item xml:lang="en">Contents</item>
        <item xml:lang="ar">المحتويات</item>
        <item xml:lang="de">Inhalt</item>
        <item xml:lang="fr">Sommaire</item>
        <item xml:lang="fi">Sisältö</item>
        <item xml:lang="da">Indholdsfortegnelse</item>
        <item xml:lang="no">Innhold</item>
        <item xml:lang="nl">Inhoudsopgave</item>
        <item xml:lang="it">Indice</item>
        <item xml:lang="es">Índice</item>
        <item xml:lang="pt">Índice</item>
        <item xml:lang="el">Περιεχόμενα</item>
        <item xml:lang="pl">Spis treści</item>
        <item xml:lang="ru">Содержание</item>
        <item xml:lang="cs">Obsah</item>
        <item xml:lang="hu">Tartalom</item>
        <item xml:lang="tr">İçindekiler</item>
        <item xml:lang="fr-CA">Sommaire</item>
        <item xml:lang="sv">Innehåll</item>
        <item xml:lang="pt-BR">Sumário</item>
        <item xml:lang="es-LAM">Contenido</item>
        <item xml:lang="bg">Съдържание</item>
        <item xml:lang="et">Sisukord</item>
        <item xml:lang="he">תוכן</item>
        <item xml:lang="hr">Sadržaj</item>
        <item xml:lang="is">Efnisyfirlit</item>
        <item xml:lang="lt">Turinys</item>
        <item xml:lang="lv">Saturs</item>
        <item xml:lang="ro">Cuprins</item>
        <item xml:lang="sk">Obsah</item>
        <item xml:lang="sl">Vsebina</item>
        <item xml:lang="sr-LAT">Sadržaj</item>
        <item xml:lang="sr-CYR">Садржај</item>
        <item xml:lang="uk">Зміст</item>
        <item xml:lang="af">Inhoud</item>
        <item xml:lang="fa">فهرست مطالب</item>
        <item xml:lang="hi"/>
        <item xml:lang="id">Daftar Isi</item>
        <item xml:lang="ja"/>
        <item xml:lang="km"/>
        <item xml:lang="ko"/>
        <item xml:lang="ms"/>
        <item xml:lang="sh"/>
        <item xml:lang="st">Dikahare</item>
        <item xml:lang="sw">Yaliyomo</item>
        <item xml:lang="th">สารบัญ</item>
        <item xml:lang="tl">Mga Nilalaman</item>
        <item xml:lang="ur">فہرست اجزا</item>
        <item xml:lang="vi">Muûc luûc</item>
        <item xml:lang="xh">IsiQulatho</item>
        <item xml:lang="zh-CN">目录</item>
        <item xml:lang="zh-HK">目錄</item>
        <item xml:lang="zh-TW">目錄</item>
        <item xml:lang="zu">Okuqukethwe</item>
      </text_before>
      <text_after/>
    </context>
    <context>
      <lookup_key>#index</lookup_key>
      <text_before>
        <default_item>{Index not translated}</default_item>
        <item xml:lang="en">Index</item>
        <item xml:lang="ar">الفهرس</item>
        <item xml:lang="tl">Indeks</item>
        <item xml:lang="de">Index</item>
        <item xml:lang="fr">Index</item>
        <item xml:lang="fi">Hakemisto</item>
        <item xml:lang="da">Indeks</item>
        <item xml:lang="no">Stikkordregister</item>
        <item xml:lang="nl">Index</item>
        <item xml:lang="it">Indice analitico</item>
        <item xml:lang="es">Índice alfabético</item>
        <item xml:lang="pt">Índice remissivo</item>
        <item xml:lang="el">Ευρετήριο</item>
        <item xml:lang="pl">Indeks</item>
        <item xml:lang="ru">Алфавитный указатель</item>
        <item xml:lang="cs">Rejstřík</item>
        <item xml:lang="hu">Mutató</item>
        <item xml:lang="tr">Dizin</item>
        <item xml:lang="fr-CA">Index</item>
        <item xml:lang="sv">Index</item>
        <item xml:lang="pt-BR">Índice</item>
        <item xml:lang="es-LAM">Índice</item>
        <item xml:lang="bg">Индекс</item>
        <item xml:lang="et">Register</item>
        <item xml:lang="he">אינדקס</item>
        <item xml:lang="hr">Kazalo</item>
        <item xml:lang="is">Atriðaskrá</item>
        <item xml:lang="lt">Rodyklė</item>
        <item xml:lang="lv">Alfabētiskais rādītājs</item>
        <item xml:lang="ro">Index</item>
        <item xml:lang="sk">Register</item>
        <item xml:lang="sl">Kazalo</item>
        <item xml:lang="sr-LAT">Indeks</item>
        <item xml:lang="sr-CYR">Индекс</item>
        <item xml:lang="uk">Покажчик</item>
        <item xml:lang="af">Indeks</item>
        <item xml:lang="fa">فهرست</item>
        <item xml:lang="hi"/>
        <item xml:lang="id">Indeks</item>
        <item xml:lang="ja"/>
        <item xml:lang="km"/>
        <item xml:lang="ko"/>
        <item xml:lang="ms"/>
        <item xml:lang="sh"/>
        <item xml:lang="st">Indekse</item>
        <item xml:lang="sw">Faharasa</item>
        <item xml:lang="th">ดัชนี</item>
        <item xml:lang="tl">Indise</item>
        <item xml:lang="ur">انڈيکس</item>
        <item xml:lang="vi">Tæì muûc</item>
        <item xml:lang="xh">Isalathisi</item>
        <item xml:lang="zh-CN">索引</item>
        <item xml:lang="zh-HK">索引</item>
        <item xml:lang="zh-TW">索引</item>
        <item xml:lang="zu">Izikhombo</item>
      </text_before>
      <text_after/>
    </context>
    <context>
      <lookup_key>#glossary</lookup_key>
      <text_before>
        <default_item>{glossary not translated}</default_item>
        <item xml:lang="en">Glossary</item>
        <item xml:lang="ar">قاموس المصطلحات</item>
        <item xml:lang="de">Glossar</item>
        <item xml:lang="fr">Glossaire</item>
        <item xml:lang="fi">Sanasto</item>
        <item xml:lang="da">Ordliste</item>
        <item xml:lang="no">Ordliste</item>
        <item xml:lang="nl">Woordenlijst</item>
        <item xml:lang="it">Glossario</item>
        <item xml:lang="es">Glosario</item>
        <item xml:lang="pt">Glossário</item>
        <item xml:lang="el">Γλωσσάριο</item>
        <item xml:lang="pl">Słownik</item>
        <item xml:lang="ru">Глоссарий</item>
        <item xml:lang="cs">Glosář</item>
        <item xml:lang="hu">Szójegyzék</item>
        <item xml:lang="tr">Sözlük</item>
        <item xml:lang="fr-CA">Glossaire</item>
        <item xml:lang="sv">Ordlista</item>
        <item xml:lang="pt-BR">Glossário</item>
        <item xml:lang="es-LAM">Glosario</item>
        <item xml:lang="bg">Речник</item>
        <item xml:lang="et">Mõisted</item>
        <item xml:lang="he">מילון מונחים</item>
        <item xml:lang="hr">Rječnik</item>
        <item xml:lang="is">Orðalisti</item>
        <item xml:lang="lt">Terminų paaiškinimai</item>
        <item xml:lang="lv">Skaidrojošā vārdnīca</item>
        <item xml:lang="ro">Glosar</item>
        <item xml:lang="sk">Výklad termínov</item>
        <item xml:lang="sl">Slovarček</item>
        <item xml:lang="sr-LAT">Glosar</item>
        <item xml:lang="sr-CYR">Глосар</item>
        <item xml:lang="uk">Глосарій</item>
        <item xml:lang="af">Woordelys</item>
        <item xml:lang="fa">واژه نامه</item>
        <item xml:lang="hi"/>
        <item xml:lang="id">Daftar istilah</item>
        <item xml:lang="ja"/>
        <item xml:lang="km"/>
        <item xml:lang="ko"/>
        <item xml:lang="ms"/>
        <item xml:lang="sh"/>
        <item xml:lang="st">Pokello ya mantswe</item>
        <item xml:lang="sw">Maneno Yaliyotumika</item>
        <item xml:lang="th">อภิธานศัพท์</item>
        <item xml:lang="tl">Glosaryo</item>
        <item xml:lang="ur">فہرست مصطلحات</item>
        <item xml:lang="vi">Baíng chuï giaíi</item>
        <item xml:lang="xh">Uluhlu lwamagama</item>
        <item xml:lang="zh-CN">词汇</item>
        <item xml:lang="zh-HK">詞彙表</item>
        <item xml:lang="zh-TW">詞彙</item>
        <item xml:lang="zu">Uhla Lwamagama</item>
      </text_before>
      <text_after/>
    </context>
    <context>
      <lookup_key>#all-rights-reserved</lookup_key>
      <text_before>
        <default_item>{#all-rights-reserved not translated}</default_item>
        <item xml:lang="en">ThreeInitialCorp. All rights reserved.</item>
        <item xml:lang="ar">ThreeInitialCorp جميع الحقوق محفوظة.</item>
        <item xml:lang="de">ThreeInitialCorp. Alle Rechte vorbehalten.</item>
        <item xml:lang="fr">ThreeInitialCorp. Tous droits réservés.</item>
        <item xml:lang="fi">ThreeInitialCorp. Kaikki oikeudet pidätetään.</item>
        <item xml:lang="da">ThreeInitialCorp. Alle rettigheder forbeholdes.</item>
        <item xml:lang="no">ThreeInitialCorp. Alle rettigheter forbeholdt.</item>
        <item xml:lang="nl">ThreeInitialCorp. Alle rechten voorbehouden.</item>
        <item xml:lang="it">ThreeInitialCorp. Tutti i diritti sono riservati.</item>
